content/urls.py
from django.urls import path

from content import views

app_name = 'content'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('add_article/', views.add_article, name='add_article'),
    path('article_logic/', views.article_logic, name='article_logic'),
    path('add_course/', views.add_course, name='add_course'),
    path('course_logic/', views.course_logic, name='course_logic'),
    path('modify/', views.modify, name='modify'),
    path('modify_logic/', views.modify_logic, name='modify_logic'),
    path('delete/', views.delete, name='delete'),
]

reception/urls.py
from django.urls import path

from reception import views

app_name = 'reception'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('check_user_name/', views.check_user_name, name='check_name'),
    path('get_captcha/', views.get_captcha, name='captcha'),
    path('check_captcha/', views.check_captcha, name='check'),
    path('register_logic/', views.register_logic, name='reg_logic'),
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('active/', views.active, name='active'),
    path('reactive/', views.reactive, name='reactive'),
    path('forget_pwd/', views.forget, name='forget'),
    path('forget_logic/', views.forget_logic, name='forget_logic'),
    path('reset_pwd/', views.reset_pwd, name='reset_pwd'),
    path('reset_logic/', views.reset_logic, name='reset_logic'),
    path('logout/', views.logout, name='logout'),
]

reception/models.py
from django.db import models

# Create your models here.


class UsersTable(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=64)
    email = models.CharField(max_length=20)
    salt = models.CharField(max_length=36)
    activation = models.BooleanField(default=False)

    class Meta:
        managed = False
        db_table = 'cms_users_table'
        unique_together = ('username',)

reception/views.py
import random
import string
import traceback
import uuid
import hashlib
import re

from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer, SignatureExpired
from BaiZhiCMS import settings
from reception.captcha.image import ImageCaptcha
from reception.models import UsersTable


def encryption(pwd, salt):
    hl = hashlib.sha256()  # 创建加密对象
    hl.update((pwd + salt).encode())  # 进行加密
    return hl.hexdigest()  # 返回加密内容


def send_email(user_id, objective='active'):
    # 传入id和目的(视图函数地址) 发送邮件
    try:
        ser = Serializer(settings.SECRET_KEY, expires_in=600)  # 声明一个对象
        token = ser.dumps({'id': user_id}).decode()  # 加密后的令牌 返回值为bytes 转为字符串
        title = '百知后台课程管理系统邮件'
        content = 'http://127.0.0.1:8000/reception/'+objective+'/?token='+token
        send = settings.EMAIL_HOST_USER
        receive = ['994225582@qq.com', ]
        send_mail(title, content, send, receive, fail_silently=False)
        return True
    except Exception as e:
        print(e)
        traceback.print_exc()


def active(request):
    token = request.GET.get("token")
    try:
        ser = Serializer(settings.SECRET_KEY, expires_in=600)  # 声明对象
        user_id = ser.loads(token).get("id")  # 从字典中获取值
        with transaction.atomic():
            user = UsersTable.objects.get(pk=user_id)
            if user.activation:
                return HttpResponse(user.username + '账户已经激活了')
            else:
                user.activation = True
                user.save()
                return HttpResponse('恭喜' + user.username + '账户被成功激活')
    except SignatureExpired:
        return HttpResponse('不好意思，链接已经失效！')
    except Exception as e:
        print(e)
        traceback.print_exc()
    return HttpResponse("激活失败")


def reactive(request):
    username = request.GET.get('username')
    user = UsersTable.objects.filter(username=username)
    if user:
        if send_email(user[0].id):
            return HttpResponse('sent')
    return HttpResponse('failed')


def register(request):
    return render(request, 'reception/register.html')


def get_captcha(request):  # 获取验证码
    img = ImageCaptcha()  # 创建验证码图片对象
    code = ''.join(random.sample(string.ascii_letters + string.digits, 4))  # 创建验证码
    request.session['code'] = code  # 保存验证码，待提交验证
    return HttpResponse(img.generate(code), 'image/png')  # 将验证码生成图片并返回验证码图片


def check_captcha(request):  # 验证验证码
    captcha = request.GET.get('captcha') or ''  # 获取用户输入的验证码
    return HttpResponse(captcha.lower() == request.session.get('code').lower())  # 返回验证结果


def check_user_name(request):  # 检查用户名是否存在
    user_name = request.GET.get('user_name')  # 获取用户输入的用户名
    return HttpResponse(bool(UsersTable.objects.filter(username=user_name)))  # 返回检查结果


def register_logic(request):  # 注册业务
    user_name = request.POST.get('user_name')
    pwd = request.POST.get('pwd')
    user_rst = re.findall(r'^[\u4e00-\u9fa5]{2,10}$', user_name)
    pwd_rst = re.findall(r'^\w{6,18}$', pwd)
    if user_rst and pwd_rst:  # 验证用户名密码是否合法
        salt = str(uuid.uuid4())  # 生成盐
        pwd = encryption(pwd, salt)  # 加密
        email = request.POST.get('email')
        try:
            with transaction.atomic():
                # 添加用户
                rst = UsersTable.objects.create(username=user_name, password=pwd, email=email, salt=salt)
                if rst:  # 如果添加成功则发送激活邮件
                    if send_email(rst.id):
                        return HttpResponse('success')
                    return HttpResponse('Failed to send mail')
        except Exception as e:
            print(e)
    return HttpResponse('fail')


def login(request):
    if request.COOKIES.get('login'):
        name = request.session['username']
        pwd = request.session['pwd']
        rst = UsersTable.objects.filter(username=name, password=pwd)
        if rst:
            request.session['id'] = {}
            return redirect('content:home')
    return render(request, 'reception/login.html')


def login_logic(request):
    username = request.POST.get('username')  # 获取用户名
    user = UsersTable.objects.filter(username=username)  # 根据用户名查找用户
    if user:  # 如果用户存在：
        pwd = encryption(request.POST.get('pwd'), user[0].salt)  # 对用户输入的密码加密
        if user[0].password == pwd:  # 如果加密后的密码与用户密码一致：
            response = HttpResponse('success')  # 创建返回对象“成功”
            if user[0].activation:  # 判断用户是否激活
                response.set_cookie('login', 'true')  # 设置登录状态为已登录
                request.session['username'] = username
                request.session['pwd'] = pwd
                request.session['id'] = {}
                if request.POST.get('remember') == 'true':  # 判断是否自动登录
                    response.set_cookie('login', 'true', max_age=7 * 24 * 3600)
            else:  # 未激活
                response = HttpResponse('not active')
            return response
    return HttpResponse('fail')


def forget(request):
    return render(request, 'reception/forget_pwd.html')


def forget_logic(request):  # 忘记密码验证
    # 获取用户名和邮箱并验证
    username = request.POST.get('user_name')
    email = request.POST.get('email')
    user = UsersTable.objects.filter(username=username, email=email)
    if user:
        if send_email(user[0].id, objective='reset_pwd'):  # 如果输入正确则发送重置密码邮件
            return HttpResponse('sent')
        return HttpResponse('Failed to send mail')
    return HttpResponse('fail')


def reset_pwd(request):
    token = request.GET.get("token")
    try:
        ser = Serializer(settings.SECRET_KEY, expires_in=600)
        user_id = ser.loads(token).get("id")
        if UsersTable.objects.filter(pk=user_id):
            request.session['user_id'] = user_id
            return render(request, 'reception/reset_pwd.html')
        return HttpResponse('token无效！')
    except SignatureExpired:
        return HttpResponse('不好意思，链接已经失效！')


def reset_logic(request):
    user_id = request.session.get('user_id')
    try:
        with transaction.atomic():
            user = UsersTable.objects.get(pk=user_id)
            pwd = request.POST.get('user_pwd')
            user.password = encryption(pwd, user.salt)
            user.save()
            del request.session['user_id']
            return HttpResponse('success')
    except Exception as e:
        traceback.print_exc()
        print(e)
    return HttpResponse('fail')


def logout(request):
    render(request, 'reception/logout.html')

templates/reception/forget_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-忘记密码</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
	<style type="text/css">
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
</head>
<body>
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}" alt="logo"></a>
        <div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>密码找回</h1>
        </div>
        <div class="reg_form clearfix">
            <form action="javascript:void(0)">
            {% csrf_token %}
            <ul>
                <li>
                    <label>用户名:</label>
                    <input type="text" name="user_name" id="user_name" placeholder="请输入用户名">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>邮箱:</label>
                    <input type="text" name="email" id="email" placeholder="请输入邮箱">
                    <span class="error_tip">提示信息</span>
                </li>
                <li class="reg_sub">
                    <input type="submit" value="提交" name="">
                </li>
            </ul>
            </form>
        </div>

    </div>

</div>
<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

<script type="text/javascript">
    $submit=$(':submit');
    $submit.click(function () {
        $submit.attr('disabled',true);
        $.ajax({
            type:'POST',
            url:'{% url 'reception:forget_logic' %}',
            data:$('form').serialize(),
            success:function (data) {
                if (data==='sent'){
                    window.alert('提交成功，请检查邮箱');
                    window.location.href='{% url 'reception:login' %}';
                }else if (data==='fail') {
                    window.alert('用户名或邮箱错误');
                }else {
                    window.alert('邮件发送失败，请稍后再试');
                }
                $submit.attr('disabled',false);
            }
        });
    });
</script>
</body>
</html>

templates/reception/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a class="login_logo" style="font-size: 30px;">
            <img src="{% static 'images/bz_logo.gif' %}" alt="logo">
            <span style="color:black;font-size: 15px;">站在时代风口，抢占人工智能</span>
        </a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">百知教育 · 课程系统</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'reception:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="javascript:void(0)">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">错误提示</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">错误提示</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember">
							<label>记住用户名</label>
							<a href="{% url 'reception:forget' %}">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        $submit=$(':submit');
        $submit.click(function () {
            $submit.attr('disabled',true);
            $.ajax({
                type:'POST',
                url:'{% url 'reception:login_logic' %}',
                data:$('form').serialize(),
                success:function (data) {
                    if (data==='success'){
                        window.location.href='{% url 'content:home' %}?home=home';
                    }else if (data==='fail') {
                        window.alert('用户名或密码错误')
                    }else {
                        if (window.confirm('账号未被激活，是否重新发送邮件')){
                            $.ajax({
                                type:'get',
                                url:'{% url 'reception:reactive' %}',
                                data:'username='+$("[name='username']").val(),
                                success:function (data) {
                                    if (data==='sent'){
                                        window.alert('邮件发送成功');
                                    }else {
                                        window.alert('邮件发送失败');
                                    }
                                }
                            });
                        }
                    }
                    $submit.attr('disabled',false);
                }
            });
        });
    </script>
</body>
</html>

templates/reception/logout.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bodymain.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/logout.css' %}"/>
        <script src="{% static 'js/jquery.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
        <title>百知课程后台管理系统-退出</title>
    </head>
    <body>
        <div class="login_top clearfix">
            <a class="login_logo" style="font-size: 30px;">
                <img src="{% static 'images/bz_logo.gif' %}" alt="logo">
                <span style="color:black;font-size: 15px;">站在时代风口，抢占人工智能</span>
            </a>
        </div>
        <div class="content-logout"></div>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-heart-empty glyphicon"></span> 关注我们</h4>
                            <p>最受欢迎的管理平台</p>
                            <p><a href="#" class="ic_df"> 新浪微博</a> </p>
                            <p><a href="#" class="ic_weichat"> 官方微信</a> </p>
                          </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-king"> 开发平台</span> </h4>
                            <p>加入开发平台，尊享会员福利，成为资深程序猿</p>
                            <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">我要开发</a></p>
                          </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-phone-alt"></span> 关于我们</h4>
                            <p>欢迎反馈宝贵意见</p>
                            <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">意见反馈</a></p>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 cp_info">
                        <div class="no-mp">
                            <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
                            <p>电话：010-****888    京ICP备*******8号</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box cotainer">
        	<div class="modal modal-free" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        
					        <h4 class="modal-title" id="myModalLabel">成功退出</h4>
					      </div>
					      <div class="modal-body">
					        感谢您今天在本站花费了一些宝贵时间！
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default my-btn" data-dismiss="modal">关闭窗口</button>
					        <a href="login.html" class="btn btn-default my-btn">重新登录</a>
					      </div>
					    </div>
					  </div>
					</div>
        </div>
<script type="text/javascript">
    $(function(){
        $(".modal-header .close").click(function(){
            $("#myModal").modal("hide");
        });
    });
</script>
    </body>
</html>

templates/reception/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}" charset="utf-8"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}" charset="utf-8"></script>
</head>
<body>
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}" alt="logo"></a>
        <div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>用户注册</h1>
            <a href="{% url 'reception:login' %}">登录</a>
        </div>
        <div class="reg_form clearfix">
            <form action="javascript:void(0)">
            {% csrf_token %}
            <ul>
                <li>
                    <label>用户名:</label>
                    <input type="text" name="user_name" id="user_name" placeholder="请输入真实姓名">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>密码:</label>
                    <input type="password" name="pwd" id="pwd" placeholder="请输入密码">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>确认密码:</label>
                    <input type="password" name="cpwd" id="cpwd" placeholder="请输入确认密码">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>邮箱:</label>
                    <input type="text" name="email" id="email" placeholder="请输入邮箱">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>验证码:</label>
                    <input type="text" name="captcha" id="captcha" style="width: 100px;">
                    <img src="{% url 'reception:captcha' %}" alt="验证码" width="100" height="40" id="captcha_img">
                    <a href="javascript:void(0)" style="text-decoration: underline;" id="change_img">看不清，换一张</a>
                    <span class="error_tip" id="tip_captcha" style="height: 27px">提示信息</span>
                </li>
                <li class="agreement">
                    <input type="checkbox" name="allow" id="allow" checked="checked">
                    <label>同意“百知课程管理系统使用协议”</label>
                    <span class="error_tip2">提示信息</span>
                </li>
                <li class="reg_sub">
                    <input type="submit" value="注 册" name="">
                </li>
            </ul>
            </form>
        </div>

    </div>

</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

<script type="text/javascript" charset="utf-8">
    var check_captcha=false;  // 设置用户名和验证码检查通过状态
    var check_user_name=false;
    function image(url){
        return '<img src="'+url+'" style="height: 16px;width: 16px;">'
    }
    $('#change_img').click(function () {  // 换一张验证码
        $('#captcha_img').attr("src","{% url 'reception:captcha' %}?time="+(new Date()).getTime());
    });
    var $captcha=$('#captcha');
    var $tip_captcha=$('#tip_captcha');
    $captcha.blur(function () {  // 验证码框失去焦点时发送ajax请求验证验证码
        var len=$captcha.val().length;
        if (len===0){
            $tip_captcha.text('验证码不能为空');
        }else {
            $tip_captcha.html(image('{% static 'images/5-121204193934-50.gif' %}'));
            $.ajax({
                type:'get',
                url:'{% url 'reception:check' %}',
                data:'captcha='+$captcha.val(),
                success:function (data) {
                    if (data==='True'){  // 判断响应结果并设置相应内容
                        $tip_captcha.html(image('{% static 'images/right_3.jpg' %}'));
                        check_captcha=true;
                    }else {
                        $tip_captcha.html(image('{% static 'images/error_3.jpg' %}'));
                    }
                }
            });
        }
        $tip_captcha.show();
    });
    var $user_name=$('#user_name');
    $user_name.blur(function () {  // 验证用户名是否存在
        if($user_name.next().html()==='ok'){
            $user_name.next().html(image('{% static 'images/5-121204193934-50.gif' %}'));
            $user_name.next().show();
            $.ajax({
                type:'get',
                url:'{% url 'reception:check_name' %}',
                data:'user_name='+$user_name.val(),
                success:function (data) {
                    if (data==='False'){
                        $user_name.next().html(image('{% static 'images/right_3.jpg' %}'));
                        check_user_name=true;
                    }else {
                        $user_name.next().text('用户名已存在');
                    }
                }
            });
        }
    });
    var $submit=$(":submit");
    $submit.click(function () {  // ajax请求提交表单
        $submit.attr('disabled',true);
        if (check_captcha && check_user_name){  // 判断检查通过状态
            $.ajax({
                type:'POST',
                url:'{% url 'reception:reg_logic' %}',
                data:$('form').serialize(),
                success:function (data) {
                    if (data==='success'){
                        if(window.confirm('注册成功，请等待管理员审核')){
                            window.location.href='{% url 'reception:login' %}';
                        }
                    }else if (data==='Failed to send mail'){
                        window.alert('注册成功，激活邮件发送失败，请稍后重新发送')
                    }else {
                        window.alert('注册失败')
                    }
                    $submit.attr('disabled',false);
                }
            });
        }
    });
</script>

</body>
</html>

templates/reception/reset_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-重置</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
	<style type="text/css">
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
</head>
<body>
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}" alt="logo"></a>
        <div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>重置密码</h1>
        </div>
        <div class="reg_form clearfix">
            <form action="javascript:void(0)">
            {% csrf_token %}
            <ul>
                <li>
                    <label>输入密码:</label>
                    <input type="password" name="user_pwd" id="pwd" placeholder="请输入密码">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>确认密码:</label>
                    <input type="password" name="confirm_pwd" id="cpwd" placeholder="请输入确认密码">
                    <span class="error_tip">提示信息</span>
                </li>

                <li class="reg_sub">
                    <input type="submit" value="提交" name="">
                </li>
            </ul>
            </form>
        </div>

    </div>

</div>
<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

<script type="text/javascript">
    $submit=$(':submit');
    $submit.click(function () {
        $submit.attr('disabled',true);
        $.ajax({
            type:'POST',
            url:'{% url 'reception:reset_logic' %}',
            data:$('form').serialize(),
            success:function (data) {
                if (data==='success'){
                    window.alert('修改成功，即将跳转到登录页面');
                    window.location.href='{% url 'reception:login' %}';
                }else {
                    window.alert('修改失败');
                }
                $submit.attr('disabled',false);
            }
        });
    });
</script>
</body>
</html>