content/urls.py
from django.urls import path

from content import views

app_name = 'content'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('add_article/', views.add_article, name='add_article'),
    path('article_logic/', views.article_logic, name='article_logic'),
    path('add_course/', views.add_course, name='add_course'),
    path('course_logic/', views.course_logic, name='course_logic'),
    path('modify/', views.modify, name='modify'),
    path('modify_logic/', views.modify_logic, name='modify_logic'),
    path('delete/', views.delete, name='delete'),
]

reception/urls.py
from django.urls import path

from reception import views

app_name = 'reception'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('check_user_name/', views.check_user_name, name='check_name'),
    path('get_captcha/', views.get_captcha, name='captcha'),
    path('check_captcha/', views.check_captcha, name='check'),
    path('register_logic/', views.register_logic, name='reg_logic'),
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('active/', views.active, name='active'),
    path('reactive/', views.reactive, name='reactive'),
    path('forget_pwd/', views.forget, name='forget'),
    path('forget_logic/', views.forget_logic, name='forget_logic'),
    path('reset_pwd/', views.reset_pwd, name='reset_pwd'),
    path('reset_logic/', views.reset_logic, name='reset_logic'),
    path('logout/', views.logout, name='logout'),
]

content/models.py
from django.db import models

# Create your models here.


class CategoryTable(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'cms_category_table'


class CurriculumTable(models.Model):
    name = models.CharField(max_length=30)
    category = models.ForeignKey(CategoryTable, models.CASCADE, db_column='category')

    class Meta:
        managed = False
        db_table = 'cms_curriculum_table'


class EssayTable(models.Model):
    name = models.CharField(max_length=60)
    curriculum = models.ForeignKey(CurriculumTable, models.CASCADE, db_column='curriculum')
    submit_time = models.DateTimeField()
    content = models.TextField(null=True)
    amount_of_reading = models.IntegerField(default=0)

    class Meta:
        managed = False
        db_table = 'cms_essay_table'
        ordering = ['id']

content/views.py
import traceback

from django.core.paginator import Paginator
from django.db import transaction
from django.http import HttpResponse  # , JsonResponse
from django.shortcuts import render, redirect
from content.models import CategoryTable, CurriculumTable, EssayTable


def home(request):
    try:
        order = request.GET.get('order') or 'id'
        page_num = request.GET.get('pge') or 1
        if request.GET.get('home') == 'home':
            request.session['id'] = {}
        gid = request.GET.get('gid') or request.session['id'].get('gid')
        cid = request.GET.get('cid') or request.session['id'].get('cid')
        if gid:
            paginator = Paginator(object_list=EssayTable.objects.filter(curriculum__category_id=gid).order_by(order),
                                  per_page=5)
            url = 'content/python.html'
            request.session['id'] = {'gid': gid}
        elif cid:
            paginator = Paginator(object_list=EssayTable.objects.filter(curriculum_id=cid).order_by(order),
                                  per_page=5)
            url = 'content/pythonBase.html'
            request.session['id'] = {'cid': cid}
        else:
            paginator = Paginator(object_list=EssayTable.objects.all().order_by(order),
                                  per_page=5)
            url = 'content/home.html'
        essay = paginator.page(page_num)
        cate = CategoryTable.objects.all()
        curr = CurriculumTable.objects.all()
        data = {'essay': essay, 'category': cate, 'curriculum': curr, 'order': order}
        return render(request, url, data)
    except Exception as e:
        traceback.print_exc()
        print(e)
    redirect('reception:login')


def add_article(request):
    cate = CategoryTable.objects.all()
    curr = CurriculumTable.objects.all()
    return render(request, 'content/addArticle.html', {'cate': cate, 'curr': curr})


def article_logic(request):
    name = request.POST.get('name')
    cate = request.POST.get('cate_sel')
    time = request.POST.get('time')
    text = request.POST.get('text')
    try:
        with transaction.atomic():
            rst = EssayTable.objects.create(name=name, curriculum_id=cate, submit_time=time, content=text)
            if rst:
                return HttpResponse('success')
    except Exception as e:
        traceback.print_exc()
        print(e)
    return HttpResponse('fail')


def add_course(request):
    cate = CategoryTable.objects.all()
    return render(request, 'content/addCourse.html', {'cate': cate})


def course_logic(request):
    try:
        name = request.GET.get('name')
        course = int(request.GET.get('course'))
        with transaction.atomic():
            if course:
                cate = int(request.GET.get('cate_sel'))
                rst = CurriculumTable.objects.create(name=name, category_id=cate)
            else:
                rst = CategoryTable.objects.create(name=name)
            if rst:
                return HttpResponse('success')
    except Exception as e:
        print(e)
        traceback.print_exc()
    return HttpResponse('fail')


def modify(request):
    eid = request.GET.get('id')
    essay = EssayTable.objects.filter(pk=eid)
    if essay:
        cate = CategoryTable.objects.all()
        curr = CurriculumTable.objects.all()
        return render(request, 'content/modify.html', {'essay': essay[0],
                                                       'cate': cate,
                                                       'curr': curr})
    return HttpResponse('文章不存在')


def modify_logic(request):
    eid = request.POST.get('id')
    name = request.POST.get('name')
    cate = request.POST.get('cate_sel')
    time = request.POST.get('time')
    content = request.POST.get('content')
    try:
        with transaction.atomic():
            essay = EssayTable.objects.get(pk=eid)
            essay.name = name
            essay.curriculum_id = cate
            essay.submit_time = time
            essay.content = content
            essay.save()
            return HttpResponse('success')
    except Exception as e:
        traceback.print_exc()
        print(e)
    return HttpResponse('fail')


def delete(request):
    eid = request.GET.get('id')
    try:
        with transaction.atomic():
            rst = EssayTable.objects.filter(pk=eid)
            if rst:
                rst[0].delete()
                return HttpResponse('success')
    except Exception as e:
        traceback.print_exc()
        print(e)
    return HttpResponse('fail')

templates/content/addCourse.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" type='text/css' href="{% static 'css/bodymain.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/addArticle.css' %}">
    <script src="{% static 'js/jquery.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'js/addCourse.js' %}" type="text/javascript" charset="utf-8"></script>
    <title>百知课程后台管理系统-增加课程/分类</title>
    <style type="text/css">
    	.option_tr {
    		display: none;  
    		/*通过查看 复选框 课程类别复选框 是否选中，如果选中，直接把当前标签显示即可*/
    	}
    </style>
</head>
<body>
<nav class="navbar navbar-default nav-self">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">百知课程后台管理系统</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'reception:login' %}" role="button">登录 <span class="glyphicon glyphicon-log-in"></span></a>
                </li>
                <li>
                    <a href="{% url 'reception:logout' %}">退出 <span class="glyphicon glyphicon-log-out"></span></a>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="">
                </div>
                <div class="btn-group" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <!-- Nav tabs -->
        <div class="panel-group col-sm-2 left-side-bar" id="accordion" role="tablist" aria-multiselectable="true">
            <div>
                <div class="panel panel-default">
                  <div class="panel-heading left-side-header"><a href="home.html">百知课程</a></div>
                  <h5 class="course-python"><a href="python.html">Python语法</a></h5>
                  <div class="list-group">
                      <a href="pythonBase.html" class="list-group-item">Python基础</a>
                      <a href="#" class="list-group-item">Python高级</a>
                  </div>
                    <h5 class="course-h5"><a href="">Web前端</a></h5>
                    <div class="list-group">
                      <a href="#" class="list-group-item">HTML/CSS</a>
                      <a href="#" class="list-group-item">JavaScript</a>
                      <a href="#" class="list-group-item">Jquery</a>
                    </div>
                    <h5 class="course-back"><a href="">web后端</a></h5>
                    <div class="list-group">
                      <a href="#" class="list-group-item">MySQL</a>
                      <a href="#" class="list-group-item">Django</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Tab panes 详情展示面板 -->
        <div class="tab-content col-sm-10 right-side">

            <div class="panel panel-default right-side-content">
                <div class="page-header">
                  <h3>增加课程/分类</h3>
                </div>
                <form action="javascript:void(0);">
                <table class="table table-bordered">
                    <tr>
                        <td align="center" valign="middle" style="width: 390px">名称：</td>
                        <td>
                            <input type="text" class="my-inp" name="name">
                            <span style="color: red;"></span>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="middle">选择类型</td>
                        <td>
                            <input type="radio" name="course" value="0">课程名称
                            <input type="radio" name="course" value="1">课程类别名称
                            <span style="color: red;"></span>
                        </td>
                    </tr>
                    <tr class='option_tr'>
                        <td align="center" style="width: 390px">课程名称：</td>
                        <td>
                            <select name="cate_sel" class="my-sel">
                                <option value="default-cate">请选择课程名称：</option>
                                {% for foo in cate %}
                                <option value="{{ foo.id }}">{{ foo.name }}</option>
                                {% endfor %}
                            </select>
                            <span style="color: red;"></span>
                        </td>
                    </tr>
                </table>
            <!--按钮组-->
                <div class="btn-toolbar" role="toolbar" aria-label="...">
                    <div class="btn-group" role="group" aria-label="...">
                        <button type="submit" class="btn btn-default my-btn"><span class="glyphicon glyphicon-floppy-disk"></span>
                            保存
                        </button>
                    </div>
                </div>
                </form>
            </div>
            <!--分页显示-->
        </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-heart-empty glyphicon"></span> 关注我们</h4>
                    <p>最受欢迎的管理平台</p>
                    <p><a href="#" class="ic_df"> 新浪微博</a> </p>
                    <p><a href="#" class="ic_weichat"> 官方微信</a> </p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-king"> 开发平台</span> </h4>
                    <p>加入开发平台，尊享会员福利，成为资深程序猿</p>
                    <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">我要开发</a></p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-phone-alt"></span> 关于我们</h4>
                    <p>欢迎反馈宝贵意见</p>
                    <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">意见反馈</a></p>
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 cp_info">
                <div class="no-mp">
                    <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
                    <p>电话：010-****888    京ICP备*******8号</p>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" charset="utf-8">
    $submit=$(':submit');
    $submit.click(function () {
        if(check_all()){
            $submit.attr('disabled',true);
            $.ajax({
                type:'get',
                url:'{% url 'content:course_logic' %}',
                data:$('form').serialize(),
                success:function (data) {
                    if (data==='success'){
                        if (window.confirm('添加成功，是否继续添加')){
                            window.location.href='{% url 'content:add_course' %}';
                        }else {
                            window.location.href='{% url 'content:home' %}';
                        }
                    }else {
                        window.alert('添加失败');
                    }
                    $submit.attr('disabled',false);
                }
            });
         }
    });
</script>
<script src="{% static 'js/addCourse_check.js' %}" type="text/javascript" charset="utf-8"></script>
</body>
</html>

templates/content/home.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <!--<meta name="viewport"-->
          <!--content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bodymain.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/selected_page.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <title>百知课程后台管理系统-首页
    </title>
</head>
<body>
<!--导航-->
<nav class="navbar navbar-default nav-self">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">百知课程后台管理系统</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'reception:login' %}" role="button">登录 <span class="glyphicon glyphicon-log-in"></span></a>
                </li>
                <li>
                    <a href="{% url 'reception:logout' %}">退出 <span class="glyphicon glyphicon-log-out"></span></a>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="">
                </div>
                <div class="btn-group" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</nav>
<!--内容面板-->
<div class="container-fluid">
    <div class="row">
        <!-- Nav tabs -->
        <div class="panel-group col-sm-2 left-side-bar" id="accordion" role="tablist" aria-multiselectable="true">
            <div>
                <div class="panel panel-default">
                  <div class="panel-heading left-side-header"><a href="{% url 'content:home' %}?home=home">百知课程</a></div>
                    {% for cate in category %}
                        <h5 class="course-python"><a href="{% url 'content:home' %}?gid={{ cate.id }}" class="header">{{ cate.name }}</a></h5>
                        <div class="list-group">
                        {% for curr in curriculum %}
                            {% if curr.category.id == cate.id %}
                                <a href="{% url 'content:home' %}?home=home&cid={{ curr.id }}" class="list-group-item">{{ curr.name }}</a>
                            {% endif %}
                        {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Tab panes 详情展示面板 -->
        <div class="tab-content col-sm-10 right-side">

            <div class="panel panel-default right-side-content">
                <div class="page-header">
                  <h3>博客文章</h3>
                </div>
                <div class="panel-body caret_parent">
                    <a href="{% url 'content:home' %}?order=-amount_of_reading" class="btn btn-default">阅读量 <span class="glyphicon glyphicon-arrow-down"></span></a>
                    <a href="{% url 'content:home' %}?order=-submit_time" class="btn btn-default">发布时间 <span class="glyphicon glyphicon-arrow-down"></span></a>
                    <a href="{% url 'content:add_article' %}" class="btn pull-right base-color add-course"><span class="glyphicon glyphicon-plus"></span> 增加文章</a>
                    <a href="{% url 'content:add_course' %}" class="btn pull-right base-color"><span class="glyphicon glyphicon-plus"></span> 增加课程/分类</a>
                </div>
                <div class="panel-heading">文章列表</div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox"/></th>
                            <th>ID</th>
                            <th>文章标题</th>
                            <th>所属课程</th>
                            <th>发布日期</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for foo in essay %}
                        <tr>
                            <td><input type="checkbox" class="checks" value="{{ foo.id }}"></td>
                            <td>{{ foo.id }}</td>
                            <td><a href="{% url 'content:modify' %}?id={{ foo.id }}">{{ foo.name }}</a></td>
                            <td>{{ foo.curriculum.name }}</td>
                            <td>{{ foo.submit_time }}</td>
                            <td><button class="btn btn-warning" value="{{ foo.id }}" onclick="del(this)">删除</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="Page navigation" class="pull-right pagitor-manager">
                    <ul class="pagination">
                        {% if essay.has_previous %}
                            <li>
                                <a href="{% url 'content:home' %}?pge={{ essay.previous_page_number }}&order={{ order }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        {% for foo in essay.paginator.page_range %}
                            <li>
                            {% if foo == essay.number %}
                                <a href="javascript:void(0)" id="selected_page">
                            {% else %}
                                <a href="{% url 'content:home' %}?pge={{ foo }}&order={{ order }}">
                            {% endif %}
                                {{ foo }}</a>
                            </li>
                        {% endfor %}
                        {% if essay.has_next %}
                            <li>
                                <a href="{% url 'content:home' %}?pge={{ essay.next_page_number }}&order={{ order }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!--分页显示-->
        </div>

    </div>

</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-heart-empty glyphicon"></span> 关注我们</h4>
                    <p>最受欢迎的管理平台</p>
                    <p><a href="#" class="ic_df"> 新浪微博</a> </p>
                    <p><a href="#" class="ic_weichat"> 官方微信</a> </p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-king"> 开发平台</span> </h4>
                    <p>加入开发平台，尊享会员福利，成为资深程序猿</p>
                    <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">我要开发</a></p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-phone-alt"></span> 关于我们</h4>
                    <p>欢迎反馈宝贵意见</p>
                    <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">意见反馈</a></p>
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 cp_info">
                <div class="no-mp">
                    <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
                    <p>电话：010-****888    京ICP备*******8号</p>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function del(target) {
        if (confirm('确认删除该篇文章？')){
            $(target).attr('disable', true);
            $.ajax({
                type:'get',
                url:'{% url 'content:delete' %}',
                data:'id='+target.value,
                success:function (data) {
                    if (data==='success'){
                        window.alert('删除成功');
                        window.location.reload();
                    }else {
                        window.alert('删除失败');
                    }
                    $(target).attr('disable', false);
                }
            });
        }
    }
</script>
</body>
</html>